language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - cd src
  - cp gce/settings/local.sample.env gce/settings/local.env
  - python manage.py migrate
script:
  - python manage.py test profiles
